'use client'

import { useState } from 'react'
import { Activity, ArrowRight, BarChart3, Bot, BriefcaseBusiness, Check, ChevronRight, CircleHelp, Code2, FileCheck2, FileText, Gauge, LayoutDashboard, LockKeyhole, Menu, MessageSquare, MoreHorizontal, Paperclip, Play, Plus, Send, Settings2, ShieldCheck, Sparkles, Target, Upload, UserRound, X, Zap } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import { careerLensApi, type ResumeEvaluation } from '@/lib/api'

type View = 'overview' | 'resume' | 'roadmap' | 'assistant' | 'practice'

const navItems: { id: View; label: string; icon: typeof LayoutDashboard }[] = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard },
  { id: 'resume', label: 'Resume evaluation', icon: FileText },
  { id: 'roadmap', label: 'Career roadmap', icon: Target },
  { id: 'assistant', label: 'Career assistant', icon: MessageSquare },
  { id: 'practice', label: 'Coding practice', icon: Code2 },
]

const evaluation: ResumeEvaluation = {
  score: 78,
  label: 'Strong foundation',
  strengths: ['Clear experience progression', 'Good use of measurable outcomes', 'Relevant technical skills'],
  weaknesses: ['Summary could be more role-specific', 'Two bullets are longer than recommended'],
  formatting: { status: 'Good', details: 'Readable hierarchy, consistent dates, and ATS-friendly structure.' },
  missingSkills: ['System design', 'Cloud cost optimization'],
  suggestions: ['Tailor your summary to the target role', 'Add one project that demonstrates system design'],
}

export default function Page() {
  const [view, setView] = useState<View>('overview')
  const [mobileNav, setMobileNav] = useState(false)
  const [uploaded, setUploaded] = useState(false)
  const [processing, setProcessing] = useState(false)
  const [evaluationData, setEvaluationData] = useState<ResumeEvaluation | null>(null)
  const [message, setMessage] = useState('')
  const [messages, setMessages] = useState([{ role: 'assistant', text: 'Hi Alex — I can help you turn your career goals into a practical next step. What would you like to work on today?' }])
  const [submitted, setSubmitted] = useState(false)

  const handleUpload = async () => {
    setUploaded(true); setProcessing(true); setEvaluationData(null)
    const result = await careerLensApi.evaluateResume({ fileName: 'alex-morgan-resume.pdf' })
    setEvaluationData(result); setProcessing(false)
  }

  const sendMessage = () => {
    if (!message.trim()) return
    setMessages((current) => [...current, { role: 'user', text: message }, { role: 'assistant', text: 'I would start by strengthening your system design evidence. I found a focused path in your roadmap that fits your current experience.' }])
    setMessage('')
  }

  return (
    <div className="min-h-screen bg-[#f7f8fa] text-[#172033]">
      <aside className={cn('fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-[#e6e9ef] bg-white transition-transform lg:translate-x-0', mobileNav ? 'translate-x-0' : '-translate-x-full')}>
        <div className="flex h-20 items-center justify-between border-b border-[#eef0f4] px-6">
          <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-[#1e3a5f] text-white"><Sparkles size={18} /></div><span className="text-lg font-semibold tracking-tight">CareerLens<span className="text-[#4f8cff]"> AI</span></span></div>
          <button className="text-slate-400 lg:hidden" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X /></button>
        </div>
        <div className="flex flex-1 flex-col gap-1 px-3 py-6">
          <p className="px-3 pb-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Workspace</p>
          {navItems.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => { setView(item.id); setMobileNav(false) }} className={cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium transition-colors', view === item.id ? 'bg-[#eef4ff] text-[#2866c7]' : 'text-slate-600 hover:bg-slate-50')}><Icon size={17} />{item.label}{item.id === 'assistant' && <span className="ml-auto size-2 rounded-full bg-[#4f8cff]" />}</button> })}
          <div className="mt-8 border-t border-[#eef0f4] pt-6"><p className="px-3 pb-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Account</p><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium text-slate-600 hover:bg-slate-50"><Settings2 size={17} />Settings</button><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium text-slate-600 hover:bg-slate-50"><CircleHelp size={17} />Help center</button></div>
        </div>
        <div className="m-3 rounded-xl bg-[#f5f8fc] p-3"><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-full bg-[#dbeafe] text-xs font-bold text-[#2866c7]">AM</div><div className="min-w-0"><p className="truncate text-xs font-semibold">Alex Morgan</p><p className="truncate text-[11px] text-slate-500">Software Engineer</p></div><MoreHorizontal size={16} className="ml-auto text-slate-400" /></div></div>
      </aside>

      <div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-[#e6e9ef] bg-white/95 px-5 backdrop-blur lg:px-10"><div className="flex items-center gap-3"><button className="text-slate-500 lg:hidden" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><div><p className="text-xs font-medium text-slate-500">Tuesday, September 17, 2026</p><h1 className="text-lg font-semibold tracking-tight">{view === 'overview' ? 'Good morning, Alex' : navItems.find((item) => item.id === view)?.label}</h1></div></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-full border border-[#e5e9f0] px-3 py-1.5 text-xs text-slate-500 sm:flex"><ShieldCheck size={14} className="text-emerald-600" />Your data is private</div><button className="flex size-9 items-center justify-center rounded-full border border-[#e5e9f0] bg-white text-slate-500" aria-label="Notifications"><Activity size={17} /></button></div></header>
        <main className="mx-auto max-w-[1440px] p-5 lg:p-10">{view === 'overview' && <Overview go={setView} />}{view === 'resume' && <ResumeView uploaded={uploaded} processing={processing} result={evaluationData} onUpload={handleUpload} />}{view === 'roadmap' && <Roadmap />}{view === 'assistant' && <Assistant messages={messages} message={message} setMessage={setMessage} sendMessage={sendMessage} />}{view === 'practice' && <Practice submitted={submitted} onSubmit={() => setSubmitted(true)} />}</main>
      </div>
    </div>
  )
}

function Overview({ go }: { go: (view: View) => void }) { return <div className="flex flex-col gap-8"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-medium text-[#4f8cff]">Your career, made clearer</p><h2 className="max-w-xl text-3xl font-semibold tracking-tight text-[#172033]">Build momentum with one clear next step.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">CareerLens brings your resume, goals, and practice into one focused workspace.</p></div><Button onClick={() => go('resume')} className="w-fit bg-[#1e3a5f] hover:bg-[#274b76]"><Upload data-icon="inline-start" />Evaluate a resume</Button></section><div className="grid gap-4 md:grid-cols-3"><Stat icon={Gauge} label="Resume evaluation" value="78 / 100" note="Strong foundation" accent="blue" /><Stat icon={Target} label="Roadmap progress" value="32%" note="3 of 9 milestones" accent="violet" /><Stat icon={Zap} label="Practice streak" value="4 days" note="Personal best" accent="amber" /></div><div className="grid gap-5 xl:grid-cols-[1.45fr_1fr]"><section className="rounded-2xl border border-[#e5e9f0] bg-white p-6"><div className="flex items-start justify-between"><div><h3 className="font-semibold">Your next best action</h3><p className="mt-1 text-sm text-slate-500">Small progress compounds over time.</p></div><span className="rounded-full bg-[#eef4ff] px-2.5 py-1 text-xs font-medium text-[#2866c7]">Recommended</span></div><div className="mt-6 flex flex-col gap-4 rounded-xl bg-[#f7f9fc] p-4 sm:flex-row sm:items-center"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-white text-[#4f8cff] shadow-sm"><FileCheck2 size={21} /></div><div className="flex-1"><p className="text-sm font-semibold">Strengthen your system design story</p><p className="mt-1 text-xs leading-5 text-slate-500">Complete the architecture fundamentals module, then add the project to your resume.</p></div><Button variant="outline" size="sm" onClick={() => go('roadmap')}>View path <ChevronRight data-icon="inline-end" /></Button></div></section><section className="rounded-2xl border border-[#e5e9f0] bg-white p-6"><div className="flex items-center justify-between"><h3 className="font-semibold">Recent activity</h3><button className="text-xs font-medium text-[#2866c7]">View all</button></div><div className="mt-5 flex flex-col gap-4"><ActivityRow icon={FileText} title="Resume evaluated" detail="Today, 9:42 AM" /><ActivityRow icon={Code2} title="Two Sum completed" detail="Yesterday, 4:18 PM" /><ActivityRow icon={Target} title="Roadmap updated" detail="Sep 14, 11:02 AM" /></div></section></div><PrivacyNote /></div> }
function Stat({ icon: Icon, label, value, note, accent }: { icon: typeof Gauge; label: string; value: string; note: string; accent: string }) { return <div className="rounded-2xl border border-[#e5e9f0] bg-white p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><span className={cn('flex size-8 items-center justify-center rounded-lg', accent === 'blue' ? 'bg-blue-50 text-blue-600' : accent === 'violet' ? 'bg-violet-50 text-violet-600' : 'bg-amber-50 text-amber-600')}><Icon size={17} /></span></div><p className="mt-5 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div> }
function ActivityRow({ icon: Icon, title, detail }: { icon: typeof FileText; title: string; detail: string }) { return <div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-lg bg-slate-50 text-slate-500"><Icon size={15} /></div><div><p className="text-sm font-medium">{title}</p><p className="text-xs text-slate-400">{detail}</p></div><ChevronRight size={15} className="ml-auto text-slate-300" /></div> }
function PrivacyNote() { return <div className="flex items-center gap-2 text-xs text-slate-400"><LockKeyhole size={14} />Your resume is encrypted and only used to provide your evaluation.</div> }

function ResumeView({ uploaded, processing, result, onUpload }: { uploaded: boolean; processing: boolean; result: ResumeEvaluation | null; onUpload: () => void }) { return <div className="flex flex-col gap-7"><div><p className="mb-2 text-sm font-medium text-[#4f8cff]">Resume intelligence</p><h2 className="text-3xl font-semibold tracking-tight">CareerLens Resume Evaluation Score</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Understand how clearly your resume communicates your experience. This is an educational evaluation, not an official ATS score.</p></div>{!uploaded ? <UploadCard onUpload={onUpload} /> : processing ? <ProcessingCard /> : result ? <EvaluationResult result={result} /> : null}</div> }
function UploadCard({ onUpload }: { onUpload: () => void }) { return <section className="rounded-2xl border border-dashed border-[#b9c8dc] bg-white p-8 text-center sm:p-14"><div className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-[#eef4ff] text-[#4f8cff]"><Upload size={24} /></div><h3 className="mt-5 text-lg font-semibold">Upload your latest resume</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">PDF or DOCX, up to 10 MB. We&apos;ll look at structure, clarity, strengths, and opportunities to improve.</p><Button className="mt-6 bg-[#1e3a5f] hover:bg-[#274b76]" onClick={onUpload}><Upload data-icon="inline-start" />Choose resume</Button><p className="mt-4 text-xs text-slate-400">For demo purposes, this simulates a resume upload.</p></section> }
function ProcessingCard() { return <section className="rounded-2xl border border-[#e5e9f0] bg-white p-10 text-center"><div className="mx-auto flex size-14 items-center justify-center rounded-full bg-blue-50 text-blue-600"><Activity className="animate-pulse" /></div><h3 className="mt-5 text-lg font-semibold">Reviewing your resume</h3><p className="mt-2 text-sm text-slate-500">We&apos;re checking structure, clarity, and role alignment.</p><div className="mx-auto mt-6 h-2 max-w-sm overflow-hidden rounded-full bg-slate-100"><div className="h-full w-2/3 animate-pulse rounded-full bg-[#4f8cff]" /></div></section> }
function EvaluationResult({ result }: { result: ResumeEvaluation }) { return <div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><section className="rounded-2xl border border-[#e5e9f0] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Evaluation score</p><p className="mt-1 text-3xl font-semibold">{result.score}<span className="text-base font-normal text-slate-400"> / 100</span></p></div><div className="flex size-20 items-center justify-center rounded-full border-[7px] border-[#cfe0ff] text-lg font-semibold text-[#2866c7]">{result.score}</div></div><div className="mt-5 rounded-xl bg-emerald-50 p-4"><p className="text-sm font-semibold text-emerald-800">{result.label}</p><p className="mt-1 text-xs leading-5 text-emerald-700">A solid base. Focus on targeted improvements to make your story more compelling.</p></div><div className="mt-6"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Formatting</p><div className="mt-3 flex items-center gap-2"><Check size={16} className="text-emerald-600" /><span className="text-sm font-medium">{result.formatting.status}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{result.formatting.details}</p></div></section><div className="grid gap-5 md:grid-cols-2"><InsightCard title="Strengths" items={result.strengths} tone="green" /><InsightCard title="Opportunities" items={result.weaknesses} tone="amber" /><InsightCard title="Missing skills to consider" items={result.missingSkills} tone="blue" /><InsightCard title="Suggested improvements" items={result.suggestions} tone="violet" /></div><div className="xl:col-span-2"><PrivacyNote /></div></div> }
function InsightCard({ title, items, tone }: { title: string; items: string[]; tone: string }) { return <section className="rounded-2xl border border-[#e5e9f0] bg-white p-5"><div className="flex items-center gap-2"><span className={cn('size-2 rounded-full', tone === 'green' ? 'bg-emerald-500' : tone === 'amber' ? 'bg-amber-500' : tone === 'blue' ? 'bg-blue-500' : 'bg-violet-500')} /><h3 className="text-sm font-semibold">{title}</h3></div><ul className="mt-4 flex flex-col gap-3">{items.map((item) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-600"><span className="mt-2 size-1 shrink-0 rounded-full bg-slate-300" />{item}</li>)}</ul></section> }

function Roadmap() { const nodes = [{ title: 'Define target role', detail: 'Completed', done: true }, { title: 'Close skill gaps', detail: 'In progress · 32%', done: false }, { title: 'Build proof of work', detail: '3 projects recommended', done: false }, { title: 'Practice interviews', detail: 'Unlocks after skills', done: false }]; return <div className="flex flex-col gap-7"><div><p className="mb-2 text-sm font-medium text-[#4f8cff]">Your personalized path</p><h2 className="text-3xl font-semibold tracking-tight">Career roadmap</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">A visual plan from your goal to measurable progress. Each step unlocks the next.</p></div><section className="rounded-2xl border border-[#e5e9f0] bg-white p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">Target</p><h3 className="mt-1 text-xl font-semibold">Senior Software Engineer</h3></div><Button variant="outline" size="sm"><Settings2 data-icon="inline-start" />Edit goal</Button></div><div className="mt-10 grid gap-4 md:grid-cols-4">{nodes.map((node, index) => <div key={node.title} className="relative"><div className={cn('mb-4 flex size-10 items-center justify-center rounded-full border-2', node.done ? 'border-emerald-500 bg-emerald-50 text-emerald-600' : index === 1 ? 'border-[#4f8cff] bg-blue-50 text-[#2866c7]' : 'border-slate-200 bg-slate-50 text-slate-400')}>{node.done ? <Check size={18} /> : index + 1}</div>{index < 3 && <div className="absolute left-10 top-5 hidden h-px w-[calc(100%-1rem)] bg-slate-200 md:block" />}<h4 className="relative text-sm font-semibold">{node.title}</h4><p className="relative mt-1 text-xs leading-5 text-slate-500">{node.detail}</p></div>)}</div></section><section className="grid gap-4 md:grid-cols-3"><RoadmapCard icon={BarChart3} title="System design fundamentals" detail="Module · 4 lessons" progress="2 / 4" /><RoadmapCard icon={Code2} title="Build a scalable project" detail="Project · Portfolio proof" progress="Not started" /><RoadmapCard icon={BriefcaseBusiness} title="Senior-level interviews" detail="Practice · 12 questions" progress="Locked" /></section></div> }
function RoadmapCard({ icon: Icon, title, detail, progress }: { icon: typeof BarChart3; title: string; detail: string; progress: string }) { return <div className="rounded-2xl border border-[#e5e9f0] bg-white p-5"><div className="flex items-start justify-between"><span className="flex size-9 items-center justify-center rounded-lg bg-[#eef4ff] text-[#2866c7]"><Icon size={17} /></span><span className="text-xs text-slate-400">{progress}</span></div><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-1 text-xs text-slate-500">{detail}</p><button className="mt-5 flex items-center gap-1 text-xs font-semibold text-[#2866c7]">Open module <ArrowRight size={14} /></button></div> }

function Assistant({ messages, message, setMessage, sendMessage }: { messages: { role: string; text: string }[]; message: string; setMessage: (value: string) => void; sendMessage: () => void }) { return <div className="mx-auto flex max-w-4xl flex-col gap-7"><div><p className="mb-2 text-sm font-medium text-[#4f8cff]">Guidance when you need it</p><h2 className="text-3xl font-semibold tracking-tight">Career assistant</h2><p className="mt-2 text-sm leading-6 text-slate-500">Ask about your resume, roadmap, interview preparation, or next career decision.</p></div><section className="flex min-h-[560px] flex-col rounded-2xl border border-[#e5e9f0] bg-white"><div className="flex items-center gap-3 border-b border-[#eef0f4] p-5"><div className="flex size-9 items-center justify-center rounded-xl bg-[#eef4ff] text-[#2866c7]"><Bot size={19} /></div><div><p className="text-sm font-semibold">CareerLens assistant</p><p className="text-xs text-emerald-600">Ready to help</p></div></div><div className="flex flex-1 flex-col gap-5 overflow-y-auto p-5">{messages.map((item, index) => <div key={index} className={cn('flex max-w-[85%] gap-3', item.role === 'user' ? 'ml-auto flex-row-reverse' : '')}><div className={cn('rounded-2xl px-4 py-3 text-sm leading-6', item.role === 'user' ? 'bg-[#1e3a5f] text-white' : 'bg-[#f5f7fa] text-slate-700')}>{item.text}</div></div>)}<div className="flex flex-wrap gap-2"><button onClick={() => setMessage('How can I improve my resume for senior roles?')} className="rounded-full border border-[#e5e9f0] px-3 py-2 text-xs text-slate-600 hover:bg-slate-50">Improve my resume</button><button onClick={() => setMessage('What should I learn next?')} className="rounded-full border border-[#e5e9f0] px-3 py-2 text-xs text-slate-600 hover:bg-slate-50">What should I learn next?</button></div></div><div className="border-t border-[#eef0f4] p-4"><div className="flex items-center gap-2 rounded-xl border border-[#dfe5ee] bg-white p-2 focus-within:ring-2 focus-within:ring-blue-100"><button className="flex size-8 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-50" aria-label="Attach file"><Paperclip size={17} /></button><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.nativeEvent.isComposing && event.keyCode !== 229) sendMessage() }} placeholder="Ask a career question..." className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none" /><Button size="sm" onClick={sendMessage} aria-label="Send message"><Send data-icon="inline-start" /></Button></div><p className="mt-2 text-center text-[11px] text-slate-400">Assistant responses are guidance, not professional or hiring advice.</p></div></section></div> }

function Practice({ submitted, onSubmit }: { submitted: boolean; onSubmit: () => void }) { return <div className="flex flex-col gap-7"><div><p className="mb-2 text-sm font-medium text-[#4f8cff]">Practice with feedback</p><h2 className="text-3xl font-semibold tracking-tight">Coding practice</h2><p className="mt-2 text-sm leading-6 text-slate-500">Build confidence with deterministic test results and separate AI coaching.</p></div><div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><section className="rounded-2xl border border-[#e5e9f0] bg-white p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">Easy · Arrays</span><span className="text-xs text-slate-400">12 min</span></div><h3 className="mt-5 text-xl font-semibold">Two Sum</h3><p className="mt-3 text-sm leading-6 text-slate-600">Given an array of integers and a target, return indices of the two numbers that add up to the target.</p><div className="mt-6 rounded-xl bg-slate-50 p-4 font-mono text-xs leading-6 text-slate-600">Input: nums = [2, 7, 11, 15], target = 9<br />Output: [0, 1]</div><div className="mt-6 flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={14} className="text-emerald-600" />Your code is executed in a backend sandbox.</div></section><section className="overflow-hidden rounded-2xl border border-[#e5e9f0] bg-[#111827] text-white"><div className="flex items-center justify-between border-b border-white/10 px-5 py-3"><div className="flex items-center gap-2 text-sm"><Code2 size={16} className="text-blue-300" />solution.js</div><span className="text-xs text-slate-400">JavaScript</span></div><textarea aria-label="Code editor" defaultValue={'function twoSum(nums, target) {\n  // Write your solution here\n  \n}'} className="min-h-[280px] w-full resize-none bg-transparent p-5 font-mono text-sm leading-7 text-slate-200 outline-none" /><div className="flex items-center justify-between border-t border-white/10 px-5 py-4"><p className="text-xs text-slate-400">No code is run in your browser.</p><Button onClick={onSubmit} className="bg-[#4f8cff] hover:bg-[#3d78df]"><Play data-icon="inline-start" />Submit solution</Button></div>{submitted && <div className="border-t border-emerald-400/20 bg-emerald-400/10 p-5"><div className="flex items-center gap-2 text-sm font-semibold text-emerald-300"><Check size={16} />Deterministic tests passed</div><p className="mt-2 text-xs leading-5 text-slate-300">AI feedback: Consider using a hash map to achieve linear time complexity.</p></div>}</section></div></div> }
